### PR TITLE
Fix index setting and moving, lock track reads

### LINKED ISSUE #2: Selecting "Next Track" throws an exception
On an Aaruformat image of Aphex Twin's "Come to Daddy EP", the following error occurs when trying to play the first track and then move to the second track:

```
System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at RedBookPlayer.Player.set_CurrentIndex(UInt16 value) in B:\Programs\GitHub\RedBookPlayer\RedBookPlayer\Player.cs:line 86
   at RedBookPlayer.Player.set_CurrentTrack(Int32 value) in B:\Programs\GitHub\RedBookPlayer\RedBookPlayer\Player.cs:line 70
   at RedBookPlayer.Player.NextTrack() in B:\Programs\GitHub\RedBookPlayer\RedBookPlayer\Player.cs:line 392
   at RedBookPlayer.PlayerView.NextTrackButton_Click(Object sender, RoutedEventArgs e) in B:\Programs\GitHub\RedBookPlayer\RedBookPlayer\PlayerView.xaml.cs:line 97
   at Avalonia.Interactivity.Interactive.<AddHandler>g__InvokeAdapter|7_0[TEventArgs](Delegate baseHandler, Object sender, RoutedEventArgs args)
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__25_9(InputElement x, PointerReleasedEventArgs e)
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObserverBase.cs:line 36
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at RedBookPlayer.Program.Main(String[] args) in B:\Programs\GitHub\RedBookPlayer\RedBookPlayer\Program.cs:line 14
   ```
   
When debugging the code, it seems like the currently selected index for the track is not being set properly. This issue is not present in the original release.

### LINKED ISSUE #4: Selecting "Next Index" on a track may cause an exception
Without the "Index navigation can change track" setting enabled, if you click "Next Index" on a track where you are on the last index of the track, it will throw an exception:

```
System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=The given key '2' was not present in the dictionary.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowKeyNotFoundException[T](T key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at RedBookPlayer.Player.set_CurrentIndex(UInt16 value) in B:\Programs\GitHub\RedBookPlayer\RedBookPlayer\Player.cs:line 86
   at RedBookPlayer.Player.NextIndex(Boolean changeTrack) in B:\Programs\GitHub\RedBookPlayer\RedBookPlayer\Player.cs:line 433
   at RedBookPlayer.PlayerView.NextIndexButton_Click(Object sender, RoutedEventArgs e) in B:\Programs\GitHub\RedBookPlayer\RedBookPlayer\PlayerView.xaml.cs:line 107
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObserverBase.cs:line 36
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at Avalonia.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.HierarchyTraverser`2.Traverse(IInteractive target)
   at Avalonia.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at RedBookPlayer.Program.Main(String[] args) in B:\Programs\GitHub\RedBookPlayer\RedBookPlayer\Program.cs:line 14
```

For example, the above was generated when playing a track with only indices 0 and 1, playing index 1, and then attempting to hit "Next Index". The fix for this is to enable earlier boundary checking. If the setting mentioned above is enabled, this should go to the next track, otherwise, the button should do nothing.

### PR DESCRIPTION
**Pull request by mnadareski**
- Replaces call to `GetEnumerator().Current`, which was always returning `default(ushort)` for the index keys, with a `.Min()` in order to find the first index in the track.
- Adds actual locking around all track reads, as once the above was fixed, changing tracks had a high probability of running into cache repeats in Aaru code (concurrent invocations of non-concurrent-safe code)
- Ensure index is valid before attempting to increment or decrement the `CurrentIndex` or `CurrentTrack`

https://github.com/aaru-dps/RedBookPlayer/pull/3/commits/09f14810dd1d7f4db27819336819650d2cb0986a and https://github.com/aaru-dps/RedBookPlayer/pull/3/commits/df3d90a5309e1003f7b1eeef12c7412f0b398c61 fixes #2 
https://github.com/aaru-dps/RedBookPlayer/pull/3/commits/bc645c21f0f515b534b6b97eba118c62e5d0fae1 fixes #4

### CODE REVIEW

**Comment by mnadareski** [comment]
Tested this change with multiple Aaruformat disc dumps, not just the one that was causing issues. All discs have no notable delay in changing tracks, but there is now a found issue about changing to "next index" that can cause a crash. I'll open a separate issue for this.

**Comment by mnadareski** [comment]
Since the fix is small for the other bit and it also affects usage in a similar way, I'm wrapping it in here.

File: RedBookPlayer/Player.cs [hunk 1]
```diff
@@ -102,12 +103,12 @@ private set
 
                 if (Image != null)
                 {
-                    if (CurrentTrack < Image.Tracks.Count - 1 && CurrentSector >= Image.Tracks[CurrentTrack + 1].TrackStartSector ||
-                        CurrentTrack > 0 && CurrentSector < Image.Tracks[CurrentTrack].TrackStartSector)
+                    if ((CurrentTrack < Image.Tracks.Count - 1 && CurrentSector >= Image.Tracks[CurrentTrack + 1].TrackStartSector)
+                        || (CurrentTrack > 0 && CurrentSector < Image.Tracks[CurrentTrack].TrackStartSector))
                     {
-                        foreach (Track track in Image.Tracks)
+                        foreach (Track track in Image.Tracks.ToArray().Reverse())
```
Comment (claunia) [inline RedBookPlayer/Player.cs:109]: Just reverse should work in a `foreach`

**Review by claunia — CHANGES_REQUESTED** [review]

File: RedBookPlayer/Player.cs (hunk 1 above)
Comment (mnadareski) [reply RedBookPlayer/Player.cs:109]: Because `Image.Tracks` is `List<Track>`, without the `.ToArray` call, it results in the following error: `CS1579	foreach statement cannot operate on variables of type 'void' because 'void' does not contain a public instance or extension definition for 'GetEnumerator'`.
